#!/usr/bin/env bash
# install the nginx and then configure it to listen on the port 80
# prints "Hello World"

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
service nginx start
