#!/usr/bin/env bash
# Configure the Nginx installation then listen on the port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
