#!/usr/bin/env bash
# FizzBuzz script for the numbers from 1 - 100:
# - Display FizzBuzz if the number is the multiple of 3 and 5
# - Display Fizz if the number is the multiple of 3
# - Display Buzz if the number is the multiple of 5
# - Otherwise, display a number

for n in {1..100}
do
	if [ $(( n % 15 )) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $(( n % 3 )) -eq 0 ]
	then
		echo "Fizz"
	elif [ $(( n % 5 )) -eq 0 ]
	then
		echo "Buzz"
	else
		echo $n
	fi
done
