#!/usr/bin/env bash
# Script configure the Ubuntu server with the 
# localhost that resolves to 127.0.0.2
# facebook.com resolves to the 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
